config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.apps import PostsConfig
from posts.views import *

app_name = PostsConfig.name

urlpatterns = [
    path('', PostsListView.as_view(), name='index'),
    path('create/', PostsCreateView.as_view(), name='create'),
    path('view/<int:pk>/', PostsDetailView.as_view(), name='view'),
    path('update/<int:pk>/', PostsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostsDeleteView.as_view(), name='delete'),
    path('user_posts/', main_public, name='user_posts'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.views import *

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_phone/', get_token, name='confirm_phone'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path('delete_user_danger', delete_user_danger, name='delete_user_danger'),
    path('user_list/', get_all_users, name='user_list'),
    path('activity/<int:pk>', toggle_activity_user, name='toggle_activity_user'),
    path('resending_token/', resending_token, name='resending_token'),

    path('payment_vip/', payment_vip, name='payment_vip'),
    path('payment_success/', payment_success, name='payment_success'),
    path('payment_cancel/', payment_cancel, name='payment_cancel'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    """Модель класса User"""

    username = None
    phone = PhoneNumberField(region='RU', verbose_name='номер телефона', unique=True)
    nickname = models.CharField(max_length=200, verbose_name='псевдоним', unique=True)
    avatar = models.ImageField(upload_to='unique', verbose_name='аватар', **NULLABLE)
    city = models.CharField(max_length=30, verbose_name='город', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='активация пользователя')
    is_vip = models.BooleanField(default=False, verbose_name='VIP-клиент')
    token = models.CharField(max_length=100, verbose_name='токен', **NULLABLE)
    payment_session_id = models.CharField(max_length=300, verbose_name='ID сессии оплаты', **NULLABLE)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.nickname}'

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    """Форма для регистрации пользователя"""
    class Meta:
        model = User
        fields = ('phone', 'nickname', 'avatar', 'city', 'first_name', 'last_name', 'password1', 'password2')



class UserForm(UserChangeForm):
    """Форма для пользователя"""

    class Meta:
        model = User
        fields = ['phone', 'nickname', 'password', 'avatar', 'city', 'first_name', 'last_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()
        for field_name, field in self.fields.items():
            if field_name not in ['avatar', 'is_active_mail']:
                field.widget.attrs['class'] = 'form-control'


class GetTokenForm(forms.Form):
    """Форма получения токена от пользователя"""
    phone = forms.CharField(widget=forms.TextInput())
    token = forms.CharField(widget=forms.TextInput())


class NewTokenForm(forms.Form):
    """Форма повторной отправки токена"""
    phone = forms.CharField(widget=forms.TextInput())

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from smsaero import SmsAeroException

from users.forms import *
from users.utils import *


class RegisterView(CreateView):
    """Представление регистрации пользователя"""
    model = User
    form_class = UserRegisterForm
    template_name = "users/user_form.html"
    success_url = reverse_lazy('users:confirm_phone')

    def form_valid(self, form):
        self.object = form.save()
        phone = int(self.object.phone.as_e164[1:])
        token = token_generate()
        self.object.token = token
        self.object.save()
        try:
            send_sms(phone=phone, message=f'Код подтверждения {token}')
            print('Сообщение отправлено')
        except SmsAeroException as e:
            print(f"An error occurred: {e}")
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """Представление изменения данных пользователя"""
    model = UserRegisterForm,
    success_url = reverse_lazy('users:profile')
    login_url = reverse_lazy('users:login')
    form_class = UserRegisterForm

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def delete_user_danger(request):
    """Представление предупреждения удаления пользователя"""
    return render(request, 'users/user_delete.html')


@login_required
def delete_user(request, user_id):
    """Представление удаления пользователя"""
    user = get_object_or_404(User, pk=user_id)
    user.delete()
    return redirect(reverse('posts:index'))


@login_required
def payment_vip(request):
    """Представление платежа"""
    user = request.user
    payment_session_id = create_sessions()["id"]
    user.payment_session_id = payment_session_id
    user.save()
    link = create_sessions()["url"]
    context_data = {'link': link}
    return render(request, 'users/payment_vip.html', context_data)

@login_required
def payment_success(request):
    """Отображение страницы при успешной оплате"""

    user = request.user
    user.is_vip = True
    user.save()

    return render(request, 'users/payment_success.html')


@login_required
def payment_cancel(request):
    """Отображение страницы при отмены оплаты"""
    return render(request, 'users/payment_cancel.html')

def get_all_users(request):
    """Функция получения пользователей"""
    users = User.objects.filter(
        is_staff=False,
        is_superuser=False,
    )
    return render(request, 'users/users_list.html', {'users': users})


def toggle_activity_user(request, pk):
    """Функция активации/деактивации пользователя"""
    user_item = get_object_or_404(User, pk=pk)
    if user_item.is_active:
        user_item.is_active = False
    else:
        user_item.is_active = True
    user_item.save()

    return redirect(reverse('users:user_list'))


def get_token(request):
    """Функция получения и проверки токена от клиента"""
    if request.method == 'POST':
        entered_token = request.POST.get('token', '')
        nickname = request.POST.get('nickname', '')
        user = get_object_or_404(User, nickname=nickname)
        if str(user.token) == str(entered_token):
            user.is_active = True
            user.save()
            return redirect('users:profile')
        else:
            return HttpResponse("Код подтверждения неверный. Попробуйте еще раз.")
    return render(request, 'users/confirm_phone.html')


def resending_token(request):
    """Повторной отправки токена клиенту"""
    if request.method == "POST":
        form = NewTokenForm(request.POST)
        if form.is_valid():
            phone = form.data["phone"]
            user = User.objects.get(phone=phone)
            token = token_generate()
            user.token = token
            user.save()
            send_sms(phone, token)

            return redirect(reverse('users:confirm_phone'))

    return render(request, 'users/confirm_phone.html', {'form': NewTokenForm})

users/templates/users/confirm_phone.html
{% extends 'posts/base.html'%}

{% block content %}
<div class="container d-flex justify-content-center">
    <div class = "text-center">
        <div class="card mb-4 box-shadow" style="max-width: 36rem;">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">Проверка номера телефона</h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <input type="text" name="nickname" placeholder="Введите ваш никнейм"><br><br>
                    <input type="text" name="token" placeholder="Введите ваш код из SMS"><br><br>
                    <button type="submit" class="btn btn-outline-primary">
                        Проверить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'posts/base.html'%}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class = 'col-6'>
            <form method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class = 'col-6'>
                    <div class="card">
                        <div class="card-header">
                            <h2 class="card-title">
                                Вход
                            </h2>
                        </div>
                        <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success"> Войти </button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{%  endblock %}

users/templates/users/new_token.html
{% extends 'posts/base.html'%}

{% block content %}
    <body>
        <div class="container">
            <h2>Пожалуйста, введите данные:</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </body>

{% endblock %}

users/templates/users/payment_cancel.html
{% extends 'posts/base.html' %}

{% block content %}
<div class="col-12">
    <a href="{% url 'users:payment_vip' %}" class="btn btn-outline-primary">К оплате</a>
</div>
<div class="container d-flex justify-content-center">
    <div class = "text-center">
        <div class="card">
            <div class="card-header">
                <h2 class="my-0 font-weight-normal">Оплата не прошла. Попробуйте снова.</h2>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/payment_success.html
{% extends 'posts/base.html' %}

{% block content %}
<div class="col-12">
    <a href="{% url 'posts:index' %}" class="btn btn-outline-primary">На главное меню</a>
</div>
<div class="container d-flex justify-content-center">
    <div class = "text-center">
        <div class="card">
            <div class="card-header">
                <h2 class="my-0 font-weight-normal">Оплата прошла. Добро пожаловать в VIP!</h2>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/payment_vip.html
{% extends 'posts/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="row">
            <div class="row text-center">
                {% if not user.is_vip %}
                    <H2>VIP клиенты могут добавлять и просматривать платные публикации</H2>
                    <div class="col-12">
                        <div class="card-footer">
                            <a href="{{ link }}" class="btn btn-success">Оплатить Vip </a>
                            <a href="{% url 'posts:index' %}" class="btn btn-warning">Отмена </a>
                        </div>
                {% else %}
                    <H2>Вы уже являетесь VIP клиентом. Олплата не требуется</H2>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock %}

users/templates/users/register.html
{% extends 'posts/base.html'%}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col-6">
                <form method="post" enctype="multipart/form-data">
                        <div class="card">
                            <div class="card-header">
                                <h2 class="card-title">
                                    Регистрация
                                </h2>
                            </div>
                            <div class="card-body">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button type="submit" class="btn btn-success"> Регистрация </button>
                                    {% if butt_add %}
                                        <a href="{% url 'users:login' %}" class="btn btn-primary"> Войти </a>
                                        <a href="{% url 'users:resending_token' %}" class="btn btn-warning"> Получить новый токен </a>
                                    {% endif %}
                            </div>
                            <div class="card-footer"></div>
                        </div>
                </form>
            </div>
        </div>
    </div>
{%  endblock %}

users/templates/users/user_delete.html
{% extends 'posts/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Действительно хотите удалить Пользователя и всех его клиентов?</p>
                            <div class="card-footer">
                                <a href="{% url 'users:delete_user' user_id=user.id %}" class="btn btn-danger">Удалить </a>
                                <a href="{% url 'users:profile' %}" class="btn btn-warning">Отмена </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'posts/base.html'%}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class = 'col-6'>
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-header">
                        Мой профиль
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success"> Сохранить </button>
                    </div>
                 </div>
            </form>
            {% if user.is_authenticated %}
                <div class="card-footer">
                    <a href="{% url 'users:delete_user_danger' %}" class="btn btn-danger">Удалить пользователя </a>
                </div>
            {% endif %}
        </div>
    </div>
{%  endblock %}

users/templates/users/users_list.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="row">
    {% for user in users %}
      <div class="col-md-4">
        <div class="card shadow-sm">
          <div class="card-body">
            <p class="card-text">{{ user.first_name }} {{ user.last_name }}</p>
            <p class="card-text">Телефон: {{ user.phone }}</p>
            {% if user.is_active %}
              <a class="btn btn-warning" href="{% url 'users:toggle_activity_user' user.pk %}">Деактивировать</a>
            {% else %}
              <a class="btn btn-success" href="{% url 'users:toggle_activity_user' user.pk %}">Активировать</a>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}