config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.apps import PostsConfig
from posts.views import *

app_name = PostsConfig.name

urlpatterns = [
    path('', PostsListView.as_view(), name='index'),
    path('create/', PostsCreateView.as_view(), name='create'),
    path('view/<int:pk>/', PostsDetailView.as_view(), name='view'),
    path('update/<int:pk>/', PostsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostsDeleteView.as_view(), name='delete'),
    path('user_posts/', main_public, name='user_posts'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.views import *

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_phone/', get_token, name='confirm_phone'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path('delete_user_danger', delete_user_danger, name='delete_user_danger'),
    path('user_list/', get_all_users, name='user_list'),
    path('activity/<int:pk>', toggle_activity_user, name='toggle_activity_user'),
    path('resending_token/', resending_token, name='resending_token'),

    path('payment_vip/', payment_vip, name='payment_vip'),
    path('payment_success/', payment_success, name='payment_success'),
    path('payment_cancel/', payment_cancel, name='payment_cancel'),
]

posts/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model

NULLABLE = {'blank': True, 'null': True}

class Post(models.Model):
    """Модель публикации"""
    title = models.CharField(max_length=250, verbose_name='заголовок')
    body = models.TextField(verbose_name='текст')
    photo = models.ImageField(upload_to='posts/', verbose_name='изображение', **NULLABLE)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    is_pay = models.BooleanField(default=False, verbose_name='платная публикация')
    is_active = models.BooleanField(default=True, verbose_name='скрыть/показывать')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name="автор")

    def __str__(self):
        return

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'

posts/forms.py
from django import forms

from posts.models import Post

class StyleForMixin:
    """Миксин класс для отображения форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_pay' and field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'

class PostForm(forms.ModelForm):
    """Форма публикации"""
    class Meta:
        model = Post
        fields = ['title', 'body', 'photo', 'is_pay', 'author',]

    def __init__(self, user, *args, **kwargs, ):
        super().__init__(*args, **kwargs)
        self.user = user
        
        if not self.user.is_vip:
            del self.fields['is_pay']

posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from posts.forms import PostForm
from posts.models import Post


class PostsListView(ListView):
    """Представление списка публикаций"""
    model = Post

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return Post.objects.all()
        queryset = Post.objects.filter(is_active=True)
        return queryset


class PostsCreateView(LoginRequiredMixin, CreateView):
    """Представление создания публикации"""
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:index')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class PostsDetailView(DetailView):
    """Представление для просмотра одной публикации"""
    model = Post
    success_url = reverse_lazy('posts:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['posts'] = Post.objects.filter(id=self.kwargs.get('pk'))
        return context_data


class PostsUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для обновления одной публикации"""
    model = Post
    form_class = PostForm
    login_url = reverse_lazy('users:login')

    def get_success_url(self):
        return reverse('posts:view', args=[self.kwargs.get('pk')])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class PostsDeleteView(LoginRequiredMixin, DeleteView):
    """Представление для обновления одной публикации"""
    model = Post
    success_url = reverse_lazy('posts:index')
    login_url = reverse_lazy('users:login')


@login_required
def main_public(request):
    """Представление для отображения публикаций пользователя"""
    posts_list = Post.objects.filter(author_id=request.user.pk)
    posts_count_all = Post.objects.filter(author_id=request.user.pk).count()
    posts_count_active = Post.objects.filter(
        author_id=request.user.pk,
        is_active=True
    ).count()
    posts_count_pay = Post.objects.filter(
        author_id=request.user.pk,
        is_pay=True
    ).count()

    context_data = {
        'posts_count_all': posts_count_all,
        'posts_count_active': posts_count_active,
        'posts_count_pay': posts_count_pay,
        'posts_list': posts_list
    }

    return render(request, 'posts/user_posts.html', context_data)

posts/templates/posts/includes/inc_main_menu.html
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">BACKERS</a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li>
          <a class="nav-link px-2 link-body-emphasis" href="/">Главная</a>
        </li>
        {% if user.is_staff or user.is_superuser %}
          <li>
            <a class="nav-link px-2 link-body-emphasis" href="{% url 'users:user_list' %}">Список всех пользователей</a>
          </li>
        {% elif user.is_authenticated %}
          <li>
            <a class="nav-link px-2 link-body-emphasis" href="{% url 'posts:user_posts' %}">Мои Публикации</a>
          </li>
          {% if not user.is_vip %}
            <li>
              <a class="nav-link px-2 link-body-emphasis" href="{% url 'users:payment_vip' %}">Оплатить Vip</a>
            </li>
          {% endif %}
        {% endif %}
      </ul>

      <div class="col-md-3 col-sm-5">
        <li>
          <a class="px-2 link-body-emphasis">Ник: {{ user }}</a>
        </li>
        <li>
          {% if user.is_pay %}
            <a class="px-2 link-body-emphasis">Статус: Vip</a>
          {% elif user.is_staff and user.is_superuser %}
            <a class="px-2 link-body-emphasis">Статус: Администратор</a>
          {% elif user.is_staff %}
            <a class="px-2 link-body-emphasis">Статус: Модератор</a>
          {% else %}
            <a class="px-2 link-body-emphasis">Статус: Пользователь</a>
          {% endif %}
        </li>
      </div>

      <div class="text-end">
        {% if user.is_authenticated %}
          <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <a type="button" class="btn btn-outline-dark me-2" href="{% url 'users:profile' %}">Изменить профиль</a>
            <button type="submit" class="btn btn-warning">Выйти</button>
          </form>
        {% else %}
          <a type="button" class="btn btn-outline-dark me-2" href="{% url 'users:login' %}">Войти</a>
          <a type="button" class="btn btn-warning" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>