config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.apps import PostsConfig
from posts.views import *

app_name = PostsConfig.name

urlpatterns = [
    path('', PostsListView.as_view(), name='index'),
    path('create/', PostsCreateView.as_view(), name='create'),
    path('view/<int:pk>/', PostsDetailView.as_view(), name='view'),
    path('update/<int:pk>/', PostsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostsDeleteView.as_view(), name='delete'),
    path('user_posts/', main_public, name='user_posts'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.views import *

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_phone/', get_token, name='confirm_phone'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path('delete_user_danger', delete_user_danger, name='delete_user_danger'),
    path('user_list/', get_all_users, name='user_list'),
    path('activity/<int:pk>', toggle_activity_user, name='toggle_activity_user'),
    path('resending_token/', resending_token, name='resending_token'),

    path('payment_vip/', payment_vip, name='payment_vip'),
    path('payment_success/', payment_success, name='payment_success'),
    path('payment_cancel/', payment_cancel, name='payment_cancel'),
]

posts/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model

NULLABLE = {'blank': True, 'null': True}

class Post(models.Model):
    """Модель публикации"""
    title = models.CharField(max_length=250, verbose_name='заголовок')
    body = models.TextField(verbose_name='текст')
    photo = models.ImageField(upload_to='posts/', verbose_name='изображение', **NULLABLE)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    is_pay = models.BooleanField(default=False, verbose_name='платная публикация')
    is_active = models.BooleanField(default=True, verbose_name='скрыть/показывать')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name="автор")

    def __str__(self):
        return

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'

posts/forms.py
from django import forms

from posts.models import Post

class StyleForMixin:
    """Миксин класс для отображения форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_pay' and field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'

class PostForm(forms.ModelForm):
    """Форма публикации"""
    class Meta:
        model = Post
        fields = ['title', 'body', 'photo', 'is_pay', 'author',]

    def __init__(self, user, *args, **kwargs, ):
        super().__init__(*args, **kwargs)
        self.user = user
        
        if not self.user.is_vip:
            del self.fields['is_pay']

posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from posts.forms import PostForm
from posts.models import Post


class PostsListView(ListView):
    """Представление списка публикаций"""
    model = Post

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return Post.objects.all()
        queryset = Post.objects.filter(is_active=True)
        return queryset


class PostsCreateView(LoginRequiredMixin, CreateView):
    """Представление создания публикации"""
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:index')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class PostsDetailView(DetailView):
    """Представление для просмотра одной публикации"""
    model = Post
    success_url = reverse_lazy('posts:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['posts'] = Post.objects.filter(id=self.kwargs.get('pk'))
        return context_data


class PostsUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для обновления одной публикации"""
    model = Post
    form_class = PostForm
    login_url = reverse_lazy('users:login')

    def get_success_url(self):
        return reverse('posts:view', args=[self.kwargs.get('pk')])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class PostsDeleteView(LoginRequiredMixin, DeleteView):
    """Представление для обновления одной публикации"""
    model = Post
    success_url = reverse_lazy('posts:index')
    login_url = reverse_lazy('users:login')


@login_required
def main_public(request):
    """Представление для отображения публикаций пользователя"""
    posts_list = Post.objects.filter(author_id=request.user.pk)
    posts_count_all = Post.objects.filter(author_id=request.user.pk).count()
    posts_count_active = Post.objects.filter(
        author_id=request.user.pk,
        is_active=True
    ).count()
    posts_count_pay = Post.objects.filter(
        author_id=request.user.pk,
        is_pay=True
    ).count()

    context_data = {
        'posts_count_all': posts_count_all,
        'posts_count_active': posts_count_active,
        'posts_count_pay': posts_count_pay,
        'posts_list': posts_list
    }

    return render(request, 'posts/user_posts.html', context_data)

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>BACKERS</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% include 'posts/includes/inc_main_menu.html' %}

    <div class="pricing-header px-3 py-3 pt-md-1 pb-md-1 mx-auto text-center">
      <h1 class="display-4">Backers</h1>
      <p class="lead">Идеальное место для размещения вашего контента и заработка на нём!</p>
    </div>

    <div class="album py-5 bg-body-tertiary">
      <div class="container">
        {% block content %}

        {% endblock %}
      </div>
    </div>

    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item">
          <a href="/" class="nav-link px-2 text-body-secondary">Главная</a>
        </li>
        {% if user.is_staff or user.is_superuser %}
          <li class="nav-item">
            <a href="{% url 'users:user_list' %}" class="nav-link px-2 text-body-secondary">Список всех пользователей</a>
          </li>
        {% elif user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'posts:user_posts' %}" class="nav-link px-2 text-body-secondary">Мои Публикации</a>
          </li>
          {% if not user.is_vip %}
            <li class="nav-item">
              <a href="{% url 'users:payment_vip' %}" class="nav-link px-2 text-body-secondary">Оплатить Vip</a>
            </li>
          {% endif %}
        {% endif %}
      </ul>
      <p class="text-center text-body-secondary">&copy; 2024 FedAS_Inc</p>
    </footer>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Уверены, хотите удалить публикацию "{{ object.title }}"?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'posts:index' %}"
                               class="btn btn-warning">Отмена </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-4">
                <div class="card">
                     <div class="card-header">
                        Информация о публикации
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <img src="/media/{{ object.photo }}" class="img-fluid" alt="Адаптивное изображение">
                                </div>
                            </div>
                        </div>
                        <tr>
                            <td>Тема публикации</td>
                            <td>{{ object.title}}</td>
                        </tr>
                        <tr>
                            <td>Содержимое публикации</td>
                            <td>{{ object.body }}</td>
                        </tr>
                        <tr>
                            {% if object.is_pay %}
                                <td>Платная</td>
                            {% else %}
                                <td> Бесплатная </td>
                            {% endif %}
                                <td>Создана</td>
                            <td>{{ object.pub_date }}</td>
                        </tr>
                    </table>
                    <div class="card-body">
                        {% if user.is_superuser or user == object.author %}
                            <a href="{% url 'posts:update' object.pk %}"
                            class="btn btn-sm btn-outline-secondary">Изменить</a>
                            <a href="{% url 'posts:delete' object.pk %}" type="button"
                            class="btn btn-sm btn-danger">Удалить</a>
                        {% elif user.is_staff %}

                        {% endif %}
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">

                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class = 'col-6'>
            <form method="post" enctype="multipart/form-data">
            {{ form.media }}
                <div class = 'col-12'>
                    <div class="card">
                        <div class="card-header">
                            <h2 class="card-title">
                                {% if object %}
                                    Изменить публикацию
                                {% else %}
                                    Добавить публикацию
                                {% endif %}
                            </h2>
                        </div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                             <button type="submit" class="btn btn-success"> Cохранить </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% block content %}
    <div class="col-12 mb-5 ">
        {% if user.is_authenticated %}
            <a class="btn btn-outline-primary" href="{% url 'posts:create' %}">Добавить пост</a>
        {% else %}
            <div class="row">
                <div class="col-4"></div>
                    <div class="col-4">
                        <H6>Для добавления поста, а также просмотра платных постов войдите или зарегистрируйтесь.</H6>
                    </div>
            </div>
        {% endif %}
    </div>
    <h1 class="display-6"> Посты </h1>
    <div class="row">
        {% for object in object_list %}
            {% if object.is_pay %}
                {% if user.is_vip %}
                    <div class="col-md-4">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <p class="card-text">
                                    {{ object.title }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{% url 'posts:view' object.pk %}"
                                    class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                    {% if user == object.author %}
                                    <a href="{% url 'posts:update' object.pk %}"
                                    class="btn btn-sm btn-outline-secondary">Изменить</a>
                                    <a href="{% url 'posts:delete' object.pk %}" type="button"
                                    class="btn btn-sm btn-danger">Удалить</a>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% else %}
                <div class="col-md-4">
                    <div class="card shadow-sm">
                        <div class="card-body">
                              <p class="card-text">
                                    {{ object.title }}
                              </p>
                              <div class="d-flex justify-content-between align-items-center">
                                    <a href="{% url 'posts:view' object.pk %}"
                                    class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                              </div>
                        </div>
                    </div>
                </div>
            {% endif %}
       {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/user_posts.html
{% extends 'posts/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="row">
        <H6>Мои публикации:</H6>
            <div class="col-12">Общее количество: {{ posts_count_all }}</div>
            <div class="col-12">Активные: {{ posts_count_active }} </div>
            <div class="col-12">Платные:: {{ posts_count_pay }}</div>
        </div>
        <div class="row text-center">
            <H2>Список моих публикаций:</H2>
            <div class="col-8">
                {% for object in posts_list %}
                    <div class="col-md-4">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <div class="card-body">
                                    <table class="table">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <img src="/media/{{ object.photo }}" class="img-fluid" alt="Адаптивное изображение">
                                                </div>
                                            </div>
                                        </div>
                                        <tr>
                                            <td>Тема публикации</td>
                                            <td>{{ object.title}}</td>
                                        </tr>
                                        <tr>
                                            {% if object.is_pay %}
                                                <td>Платная</td>
                                            {% else %}
                                                <td> Бесплатная </td>
                                            {% endif %}
                                            <td>{{ object.pub_date }}</td>
                                        </tr>

                                    </table>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{% url 'posts:view' object.pk %}"
                                    class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                    <a href="{% url 'posts:update' object.pk %}"
                                    class="btn btn-sm btn-outline-secondary">Изменить</a>
                                    <a href="{% url 'posts:delete' object.pk %}" type="button"
                                    class="btn btn-sm btn-danger">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
`               {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}